name: Validate songs list

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run validator
        run: |
          set -e
          python3 --version
          if ! python3 scripts/validate_songs.py; then
            echo "Showing first 5 issues:"
            python3 scripts/validate_songs.py | awk '/^Validation issues found:/{flag=1;next} /^Checked/{flag=0} flag && /^- /{print}' | head -5
            exit 1
          fi